### ISSUE TITLE
Bail and crash when I open a new window

### ISSUE THREAD

**Issue by acrisci** [Airblader/xedgewarp#17] opened 2015-05-16 04:13 UTC
Whenever I open a window, xedgewarp bails out and crashes.

Log here:

http://pastebin.com/D1FiCBCd

The error is:

> ERROR: Received error: Could not register for events on window, bailing out.

**Comment by Airblader** [comment] 2015-05-16 13:15
Does it happen for _every_ window you open? I can open windows just fine. Which one are you opening?

I think it might be because I query the tree and then operate on all returned windows. If one of them was closed again in the meantime, it bails. Bailing is probably overkill anyway. Since I think grabbing the server for this is too, I will just demote this case to a log statement instead of bailing.

It'd be interesting to know which windows these are anyway, since it's just a theory that it gets closed in the meantime. I can probably check for that specific error and bail in other cases.

**Comment by acrisci** [comment] 2015-05-16 21:57
Any window causes the crash (urxvt, chromium, firefox).

I think the issue has to do with the window not being mapped when you try to register for events.

**Comment by Airblader** [comment] 2015-05-17 01:34
Mh, but registering for events shouldn't require the window to be mapped. In fact it's the recommended way to set event masks before mapping a window. 

I definitely can open urxvt without crash. I'll try some other applications, but I'll just change it to a log statement if setting the event mask fails due to the window not existing.

**Comment by Airblader** [comment] 2015-05-17 15:22
I reproduced it with dmenu. urxvt and thunar work fine, though.

**Comment by acrisci** [comment] 2015-05-17 18:13
I figured out how to make it work sometimes.

If I use `exec` with `--no-startup-id` with urxvt, it works fine. Also, if I run urxvt from outside of i3 such as in the terminal or dmenu, it works fine. Same with chromium.

Firefox never works.

**Comment by Airblader** [comment] 2015-05-17 18:21
Thanks for investigating. That's odd. I'd suggest we wait until I did the above mentioned fix and if it still doesn't work, we look further. 

I just have trouble imagining it's anything else since every application and every window manager does what xedgewarp does (just with different masks).

**Comment by acrisci** [comment] 2015-05-17 18:30
Are you sure about that? I can't find where i3 handles CreateNotify.

**Comment by Airblader** [comment] 2015-05-17 18:36
Sorry, I meant the fact that event masks are set before a window is mapped. See

"First, the program selects the events it wants for each window. Then it maps the windows. [...] You must make sure that every window that is to receive events appears on the screen after the events are selected for that window but before the event loop begins." — http://menehune.opt.wfu.edu/Kokua/Irix_6.5.21_doc_cd/usr/share/Insight/library/SGI_bookshelves/SGI_Developer/books/XLib_PG/sgi_html/ch08.html

If dealing with windows that don't exist anymore doesn't work, we can just take a look at the actual error type we are receiving.

**Comment by Airblader** [comment] 2015-05-18 14:29
I just tried this and it does seem to be what I expected: the window doesn't exist anymore by the time I want to register events for it.

**Comment by Airblader** [comment] 2015-05-18 14:48
@acrisci I've pushed a fix for this (https://github.com/Airblader/xedgewarp/commit/d0ea4a0db12f156a738fc72bd451230c08d1c1a9), can you please update and see if you can still produce errors?

Please note that it won't bail either way, so the log needs to be checked for an error (the bad window case is logged as debug). You also need to start it with `-l debug` now.

**Comment by acrisci** [comment] 2015-05-23 21:28
It seems to work without the errors now.

**Comment by Airblader** [comment] 2015-05-23 21:47
Great. Thanks for your help. If it happens again, please let me know :)

**Comment by acrisci** [comment] 2015-07-08 02:09
I'm getting this again occasionally.

> [src/event.c:178] DEBUG: Touching a dead border segment at 335 / 0.
> [src/pointer.c:127] DEBUG: Successfully warped pointer from 335 / 0 (647) to 335 / 1079 (647)
> [src/event.c:178] DEBUG: Touching a dead border segment at 336 / 1079.
> [src/pointer.c:127] DEBUG: Successfully warped pointer from 336 / 1079 (647) to 336 / 0 (647)
> [src/event.c:143] DEBUG: Received CreateNotify event for window 46168262
> [src/event.c:17] DEBUG: Setting event mask for window 46168262
> [src/event.c:143] DEBUG: Received CreateNotify event for window 4194590
> [src/event.c:17] DEBUG: Setting event mask for window 4194590
> X Error of failed request:  BadValue (integer parameter out of range for operation)
>   Major opcode of failed request:  131 (XInputExtension)
>   Minor opcode of failed request:  46 ()
>   Value in failed request:  0xd
>   Serial number of failed request:  31
>   Current serial number in output stream:  87377

**Comment by Airblader** [comment] 2015-07-08 06:07
Odd. I'll look into it. Did this only start happening after an update or something?

**Comment by Airblader** [comment] 2015-07-08 08:18
I think in fact that with XI2, I only need to register the root window and not all windows anyway. I'll give this a shot and if it works, I'll just do that.

**Comment by Airblader** [comment] 2015-07-08 08:30
@acrisci Can you check out the branch `bug-17-2` and see if it works? I pushed the beforementioned change on there. I'd really not expect selecting events to fail on the root window.

**Comment by acrisci** [comment] 2015-07-11 17:04
seems to work better now.

**Comment by Airblader** [comment] 2015-07-11 18:49
Great, thanks for the feedback. Merged.

**Closed as completed by Airblader** 2015-07-11 18:49 UTC
Labels: bug
